// Yetimmm bridge v4.1 — ONE bot, ONE link, login by MT5 account number + ONE app password.
//   EA  -> POST /api/ea/sync  (header X-EA-Secret, auto-generated by the EA)  body {login, srv, fresh, reset, cv, state, ack}
//   App -> POST /login        body {login, pw, init}                -> {ok, sess}
//   App -> POST /verify       headers X-Login + X-Session, body {init} -> {ok, hard, checks:{session,account,telegram,bot}}
//   App -> GET  /state        headers X-Login + X-Session
//   App -> POST /command      headers X-Login + X-Session
//   App -> POST /logout       headers X-Login + X-Session
// Secret (wrangler secret put): BOT_TOKEN
// Each MT5 account gets its own isolated hub (Durable Object "acc-<login>").
// The EA's MT5 trading password is NEVER requested or stored.

// ═════════════════════════════════════════════════════════════════════════
//  CONFIG — the ONLY place you edit. Every value can also be overridden
//  WITHOUT touching code:  wrangler secret put <NAME>   (or [vars] in wrangler.toml)
//  After you change anything: `wrangler deploy` and everything reacts automatically:
//    • password changed  -> all old sessions die by themselves (each session is bound to a password fingerprint)
//    • SESSION_EPOCH bumped -> everybody is signed out instantly (panic button)
// ═════════════════════════════════════════════════════════════════════════
const CONFIG = {
  PASSWORD: "123123",        // the app password (env APP_PASSWORD overrides it)
  LOCK_SECONDS: 120,         // lock duration after too many wrong passwords = 2 minutes
  MAX_ATTEMPTS: 8,           // wrong passwords allowed before the lock
  FAIL_WINDOW_SEC: 600,      // wrong attempts older than this are forgotten
  SESSION_DAYS: 30,          // sliding session lifetime (refreshed on every successful verify)
  EA_STALE_SEC: 20,          // EA counts as offline after this many seconds without a sync
  SESSION_EPOCH: 1,          // bump (1 -> 2) to sign EVERYONE out at once
  REQUIRE_TG: true,          // true = login only from inside the Telegram bot (env REQUIRE_TG="0" allows browsers)
};

const num = (v, d) => { const n = Number(v); return Number.isFinite(n) && n > 0 ? n : d; };
function cfg(env) {
  return {
    password: String(env.APP_PASSWORD || CONFIG.PASSWORD),
    lockMs: num(env.LOCK_SECONDS, CONFIG.LOCK_SECONDS) * 1000,
    max: Math.max(1, Math.floor(num(env.MAX_ATTEMPTS, CONFIG.MAX_ATTEMPTS))),
    winMs: num(env.FAIL_WINDOW_SEC, CONFIG.FAIL_WINDOW_SEC) * 1000,
    sessMs: num(env.SESSION_DAYS, CONFIG.SESSION_DAYS) * 86400000,
    staleSec: num(env.EA_STALE_SEC, CONFIG.EA_STALE_SEC),
    epoch: String(env.SESSION_EPOCH || CONFIG.SESSION_EPOCH),
    requireTg: String(env.REQUIRE_TG !== undefined ? env.REQUIRE_TG : CONFIG.REQUIRE_TG ? "1" : "0") !== "0",
    salt: String(env.BOT_TOKEN || ""),
  };
}

const json = (o, status = 200) =>
  new Response(JSON.stringify(o), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" } });
const enc = new TextEncoder();
const hex = (u8) => [...u8].map((b) => b.toString(16).padStart(2, "0")).join("");
const rnd = (n) => hex(crypto.getRandomValues(new Uint8Array(n)));
const sha = async (s) => hex(new Uint8Array(await crypto.subtle.digest("SHA-256", enc.encode(String(s)))));

function safeEq(a, b) {
  a = String(a || ""); b = String(b || "");
  if (!a || a.length !== b.length) return false;
  let r = 0;
  for (let i = 0; i < a.length; i++) r |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return r === 0;
}
async function hmacRaw(keyBytes, data) {
  const k = await crypto.subtle.importKey("raw", keyBytes, { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return new Uint8Array(await crypto.subtle.sign("HMAC", k, typeof data === "string" ? enc.encode(data) : data));
}
// Password fingerprint: changes the moment the password (or SESSION_EPOCH) changes. Never leaves the server.
async function pwVersion(c) { return hex(await hmacRaw(enc.encode("yt-pwv|" + c.epoch + "|" + c.salt), c.password)).slice(0, 16); }
// Constant-time password check that does not leak the password LENGTH (both sides are hashed to the same size first).
async function pwEq(c, given, real) {
  const k = enc.encode("yt-pwc|" + c.salt);
  return safeEq(hex(await hmacRaw(k, String(given || ""))), hex(await hmacRaw(k, String(real || ""))));
}
// Verifies Telegram Mini App initData with the bot token. Returns the Telegram user id or null.
async function tgUser(initData, botToken) {
  try {
    if (!initData || !botToken) return null;
    const p = new URLSearchParams(initData);
    const hash = p.get("hash");
    if (!hash) return null;
    p.delete("hash");
    const dcs = [...p.entries()].map(([k, v]) => k + "=" + v).sort().join("\n");
    const secret = await hmacRaw(enc.encode("WebAppData"), botToken);
    if (!safeEq(hex(await hmacRaw(secret, dcs)), hash)) return null;
    if (Date.now() / 1000 - Number(p.get("auth_date") || 0) > 86400) return null;
    const u = JSON.parse(p.get("user") || "{}");
    return u.id ? String(u.id) : null;
  } catch (e) { return null; }
}

function cors(req) {
  const o = req.headers.get("Origin");
  if (!o) return {};
  return { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Content-Type, X-Login, X-Session, X-EA-Secret", "Access-Control-Allow-Methods": "GET, POST, OPTIONS", Vary: "Origin" };
}

export default {
  async fetch(req, env) {
    const url = new URL(req.url);
    const ch = cors(req);
    if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: ch });
    const done = (res) => { const h = new Headers(res.headers); for (const [k, v] of Object.entries(ch)) h.set(k, v); return new Response(res.body, { status: res.status, headers: h }); };
    const P = url.pathname;
    const c = cfg(env);
    if (P === "/") return done(json({ ok: true, service: "yetimmm-bridge", v: 4 }));
    try {
      let login = "", body = "";
      if (P === "/api/ea/sync" || P === "/login") {
        body = await req.text();
        let b = {}; try { b = JSON.parse(body); } catch (e) {}
        login = String(b.login || "").trim();
      } else if (P === "/state" || P === "/command" || P === "/logout" || P === "/verify") {
        login = (req.headers.get("X-Login") || "").trim();
        if (req.method === "POST") body = await req.text();
      } else return done(json({ error: "not found" }, 404));
      if (!/^\d{3,12}$/.test(login)) return done(json({ ok: false, error: "login" }, P === "/login" ? 400 : 401));
      const hub = env.HUB.get(env.HUB.idFromName("acc-" + login));
      const call = (path, extra) => hub.fetch("https://hub" + path, { method: "POST", body: JSON.stringify(extra) });
      if (P === "/api/ea/sync") return done(await call("/sync", { secret: (req.headers.get("X-EA-Secret") || "").trim(), body, tok: env.BOT_TOKEN || "" }));
      if (P === "/login") {
        const b = JSON.parse(body);
        const tg = await tgUser(String(b.init || ""), env.BOT_TOKEN || "");
        const gate = env.HUB.get(env.HUB.idFromName("gate-" + (tg ? "tg" + tg : "ip" + (req.headers.get("CF-Connecting-IP") || "x"))));
        const gcall = async (op) => (await gate.fetch("https://hub/gate", { method: "POST", body: JSON.stringify(op) })).json();
        const g0 = await gcall({});
        if (!g0.ok) return done(json({ ok: false, error: "locked", retry: g0.retry }, 429));
        if (c.requireTg && !tg) return done(json({ ok: false, error: "tg_only" }, 403));
        if (!(await pwEq(c, b.pw, c.password))) {
          const g = await gcall({ fail: true });
          if (!g.ok) return done(json({ ok: false, error: "locked", retry: g.retry }, 429));
          return done(json({ ok: false, error: "bad_pw", left: g.left }, 401));
        }
        const res = await call("/login", { tg });
        if (res.status !== 200) { await gcall({ fail: true }); return done(res); }
        await gcall({ reset: true });
        return done(res);
      }
      const sess = (req.headers.get("X-Session") || "").trim();
      if (P === "/verify") {
        let b = {}; try { b = JSON.parse(body || "{}"); } catch (e) {}
        const tg = await tgUser(String(b.init || ""), env.BOT_TOKEN || "");
        return done(await call("/verify", { sess, tg }));
      }
      if (P === "/state") return done(await call("/state", { sess }));
      if (P === "/command") return done(await call("/command", { sess, body }));
      if (P === "/logout") return done(await call("/logout", { sess }));
    } catch (e) { return done(json({ error: "server" }, 500)); }
    return done(json({ error: "not found" }, 404));
  },
};

export class Hub {
  constructor(ctx, env) { this.ctx = ctx; this.c = cfg(env || {}); this.st = null; this.ts = 0; }
  age() { return this.ts ? (Date.now() - this.ts) / 1000 : null; }
  botUp() { const g = this.age(); return g !== null && g < this.c.staleSec; }
  async fetch(req) {
    const p = new URL(req.url).pathname;
    const b = await req.json().catch(() => ({}));
    if (p === "/gate") return this.gate(b);
    if (p === "/sync") return this.sync(b);
    if (p === "/login") return this.login(b);
    if (p === "/verify") return this.verify(b);
    if (p === "/state") return this.state(b);
    if (p === "/command") return this.command(b);
    if (p === "/logout") return this.logout(b);
    return json({ error: "not found" }, 404);
  }
  async S() {
    const a = (await this.ctx.storage.get("acc")) || { sessions: [], tg: [], cfgv: 0 };
    a.sessions = (a.sessions || []).filter((x) => x && typeof x === "object");   // v3 string sessions are dropped once
    a.tg = a.tg || [];
    return a;
  }
  // A session is valid only if: it exists (stored hashed), is not expired, belongs to the current SESSION_EPOCH,
  // was created under the CURRENT password, and the MT5 server of the account did not change since.
  async chk(a, sess) {
    if (!sess) return { why: "none" };
    const h = await sha(sess);
    const s = a.sessions.find((x) => safeEq(x.h, h));
    if (!s) return { why: "gone" };
    if (Date.now() - s.t > this.c.sessMs) return { why: "expired" };
    if (s.ep !== this.c.epoch) return { why: "revoked" };
    if (s.pwv !== (await pwVersion(this.c))) return { why: "pw" };
    if (a.srv && s.srv && a.srv !== s.srv) return { why: "acct" };
    return { s };
  }
  deny(why) { return json({ ok: false, error: "session", why }, 401); }

  // ---- EA side ----
  async sync(m) {
    let body = {}; try { body = JSON.parse(m.body || "{}"); } catch (e) {}
    const a = await this.S();
    const secret = String(m.secret || "");
    if (secret.length < 16) return json({ ok: false, error: "secret" }, 401);
    if (!a.eaSecret) a.eaSecret = secret;                 // first EA to appear on this account owns it
    else if (!safeEq(a.eaSecret, secret)) return json({ ok: false, error: "secret" }, 401);
    let dirty = false;
    const now0 = Date.now();
    // v4: an EA restart NO LONGER signs anybody out. The app re-verifies on open (account + Telegram + bot) and enters by itself.
    // Sessions are revoked only when: the EA asks explicitly (reset), or the MT5 SERVER of this account changed.
    const srv = String(body.srv || "").slice(0, 64);
    if (srv && a.srv !== srv) { if (a.srv && a.sessions.length) a.sessions = []; a.srv = srv; dirty = true; }
    if (body.reset && a.sessions.length) { a.sessions = []; dirty = true; }
    if (!a.seen || now0 - a.seen > 15000) { a.seen = now0; dirty = true; }
    // single shared bot: config v changes when the chat list or the token changes
    const tsig = hex(await hmacRaw(enc.encode("t"), m.tok || "")).slice(0, 8);
    if (a.tsig !== tsig) { a.tsig = tsig; a.cfgv = (a.cfgv || 0) + 1; dirty = true; }
    if (dirty) await this.ctx.storage.put("acc", a);
    if (body.state && typeof body.state === "object") { this.st = body.state; this.ts = Date.now(); }
    let q = (await this.ctx.storage.get("cmds")) || [];
    const ack = Array.isArray(body.ack) ? body.ack : [];
    const now = Date.now();
    const next = q.filter((x) => !ack.includes(x.c.id) && now - x.t < 120000);
    if (next.length !== q.length) await this.ctx.storage.put("cmds", next);
    const out = { ok: true, commands: next.map((x) => x.c) };
    if (String(a.cfgv) !== String(body.cv !== undefined ? body.cv : 0)) out.cfg = { v: String(a.cfgv), tok: m.tok || "", auth: a.tg.join(",") };
    return json(out);
  }

  // ---- App side ----
  async login(m) {
    const a = await this.S();
    if (!a.eaSecret || !this.botUp()) return json({ ok: false, error: "ea_offline" }, 503);   // EA must be running on this account
    const sess = rnd(24);
    const entry = { h: await sha(sess), tg: m.tg || "", t: Date.now(), pwv: await pwVersion(this.c), ep: this.c.epoch, srv: a.srv || "" };
    a.sessions = [...a.sessions, entry].slice(-10);
    if (m.tg && !a.tg.includes(m.tg)) { a.tg = [...a.tg, m.tg].slice(-5); a.cfgv = (a.cfgv || 0) + 1; }   // Telegram identity proven by Telegram itself
    await this.ctx.storage.put("acc", a);
    return json({ ok: true, sess });
  }
  // Fast connection check used by the app's "verify" popup. Four independent checks, so the UI can tell
  // a HARD failure (must sign in again) from a SOFT one (the bot is simply off right now -> keep waiting, auto-enter when it is back).
  async verify(m) {
    const a = await this.S();
    const r = await this.chk(a, m.sess);
    const bot = this.botUp() && !!a.eaSecret;
    if (!r.s) return json({ ok: false, hard: true, why: r.why, checks: { session: false, account: r.why !== "acct", telegram: false, bot } });
    const s = r.s;
    const telegram = m.tg ? s.tg === m.tg && a.tg.includes(m.tg) : !this.c.requireTg && !s.tg;
    const checks = { session: true, account: true, telegram, bot };
    const hard = !telegram;
    if (!hard) { s.t = Date.now(); await this.ctx.storage.put("acc", a); }   // sliding expiry
    return json({ ok: telegram && bot, hard, why: hard ? "tg" : "", checks });
  }
  // brute-force guard per Telegram user / IP (the password is shared, so the limit is NOT per account: that would let a stranger lock the owner out)
  // v4: a real lock — after MAX_ATTEMPTS failures the key is locked for LOCK_SECONDS (2 min) and the exact remaining time is returned.
  async gate(m) {
    const now = Date.now(), c = this.c;
    let g = (await this.ctx.storage.get("g")) || { n: 0, t: now, until: 0 };
    if (g.until && now >= g.until) g = { n: 0, t: now, until: 0 };
    if (!g.until && now - g.t > c.winMs) g = { n: 0, t: now, until: 0 };
    if (m.reset) g = { n: 0, t: now, until: 0 };
    else if (m.fail && !(g.until && now < g.until)) { g.n++; if (g.n >= c.max) g.until = now + c.lockMs; }
    const locked = !!(g.until && now < g.until);
    await this.ctx.storage.put("g", g);
    return json({ ok: !locked, retry: locked ? Math.ceil((g.until - now) / 1000) : 0, left: Math.max(0, c.max - g.n) });
  }
  async logout(m) {
    const a = await this.S();
    const h = await sha(m.sess || "");
    const mine = a.sessions.find((x) => safeEq(x.h, h));
    a.sessions = a.sessions.filter((x) => !safeEq(x.h, h));
    // signing out also removes this Telegram user's registration on the account when no other session of theirs remains
    if (mine && mine.tg && !a.sessions.some((x) => x.tg === mine.tg) && a.tg.includes(mine.tg)) { a.tg = a.tg.filter((x) => x !== mine.tg); a.cfgv = (a.cfgv || 0) + 1; }
    await this.ctx.storage.put("acc", a);
    return json({ ok: true });
  }
  async state(m) {
    const a = await this.S();
    const r = await this.chk(a, m.sess);
    if (!r.s) return this.deny(r.why);
    const ag = this.age();
    const st = this.st || { price: 0, run: false, state: "STOPPED", hist: [] };
    return json({ ...st, eaAge: ag, eaOnline: this.botUp() });
  }
  async command(m) {
    const a = await this.S();
    const r = await this.chk(a, m.sess);
    if (!r.s) return this.deny(r.why);
    let b = null; try { b = JSON.parse(m.body || "null"); } catch (e) {}
    const allowed = ["start", "stop", "close", "reset", "apply", "settings", "delete", "cancel", "modify", "place"];
    if (!b || !allowed.includes(String(b.cmd))) return json({ error: "bad command" }, 400);
    if (!this.botUp()) return json({ error: "ea offline" }, 503);
    const c = { id: crypto.randomUUID().replace(/-/g, "").slice(0, 16), cmd: String(b.cmd) };   // id first: the EA parser relies on it
    for (const k of ["buy", "sell", "risk", "target", "rr", "ticket", "price"]) {
      if (b[k] === undefined || b[k] === null || b[k] === "") continue;
      const n = Number(b[k]);
      if (!Number.isFinite(n)) return json({ error: "bad number: " + k }, 400);
      c[k] = n;
    }
    if (b.side !== undefined && b.side !== null && b.side !== "") {
      const sd = String(b.side).toUpperCase();
      if (sd !== "BUY" && sd !== "SELL") return json({ error: "bad side" }, 400);
      c.side = sd;
    }
    if ((b.cmd === "delete" || b.cmd === "modify") && !(c.ticket > 0) && !c.side) return json({ error: "ticket or side required" }, 400);
    if ((b.cmd === "modify" || b.cmd === "place") && !(c.price > 0)) return json({ error: "price required" }, 400);
    if (b.cmd === "place" && !c.side) return json({ error: "side required" }, 400);
    const q = (await this.ctx.storage.get("cmds")) || [];
    q.push({ t: Date.now(), c });
    await this.ctx.storage.put("cmds", q.slice(-20));
    return json({ ok: true, id: c.id });
  }
}
